INCLUDE=-I. -I/usr/include/libxml2 -I/usr/local/include
LDFLAGS=-lxml2 -L/usr/local/lib -ggdb -m32

OBJECTS=DomTree.o DomElement.o DomAttribute.o DomDataHandler.o

all: clean pdom test

%.o: %.cpp
	$(CXX) -c -o $@ $< $(INCLUDE)

clean:
	rm -rf *.o *.so *.dylib
	
pdom: $(OBJECTS)
	$(CXX) -shared -Wl,-soname,pdom.dll -o pdom.dll $^ $(LDFLAGS)

test: $(OBJECTS)
	$(CXX) -o test test.cpp $(LDFLAGS) $(INCLUDE) -L. -lpdom
